services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/calculator
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  mongo-data:
